server:
  port: 8080

tinger:
  jdbc:
    config:
      databases:
        tinger:
          driver: com.mysql.cj.jdbc.Driver
          jdbcUrl: jdbc:mysql://localhost:3306/tinger?useUnicode=true&characterEncoding=UTF-8
          username: root
          password: 123456
          alias:
            - apps
            - book
            - exam
            - auth
            - member_0
            - member_1
            - record_0
            - record_1
      sharding:
        tinger:
          - member_0
          - member_1
        member:
          - member_0
          - member_1
        record:
          - record_0
          - record_1