server:
  port: 8080

springdoc:
  show-actuator: false
  use-management-port: false
  api-docs:
    enabled: true
    path: /define/api.html
  swagger-ui:
    enabled: true
    path: /define/doc.html
  packages-to-scan:
    - org.tinger.web.controller.api
    - org.tinger.web.controller.venus

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include:
          - openapi
          - swagger-ui

tinger:
  jdbc:
    config:
      databases:
        tinger:
          driver: com.mysql.cj.jdbc.Driver
          jdbcUrl: jdbc:mysql://localhost:3306/tinger?useUnicode=true&characterEncoding=UTF-8
          username: root
          password: 123456
          alias:
            - apps
            - book
            - exam
            - auth
            - member_0
            - member_1
            - record_0
            - record_1
      sharding:
        tinger:
          - member_0
          - member_1
        member:
          - member_0
          - member_1
        record:
          - record_0
          - record_1